# Generated by Django 4.1.5 on 2023-01-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
