# Generated by Django 4.1.5 on 2023-01-18 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100)),
                ('artist_price', models.PositiveIntegerField()),
                ('artist_desc', models.TextField()),
                ('artist_pic', models.ImageField(upload_to='product_pic/')),
                ('artist_size', models.CharField(choices=[('singer', 'singer'), ('dancer', 'dancer'), ('photographer', 'photographer'), ('Writer', 'writer'), ('standup', 'standup'), ('influencer', 'influencer')], max_length=100)),
                ('artist_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
