# Generated by Django 4.1.5 on 2023-01-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='artist_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
