# Generated by Django 4.1.5 on 2023-02-08 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_booking_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='artist1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.artist'),
            preserve_default=False,
        ),
    ]
