# Generated by Django 4.1.5 on 2023-02-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_contacts_artist1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='artist1',
        ),
    ]
